# -*- coding: utf-8 -*-
"""250513sunoaitest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzG5gvrMqCNvFk9UpzXZTToDvtUevwEX
"""

token = "<token>"

# 태스크아이디
import requests
import json

url = "https://apibox.erweima.ai/api/v1/generate"

payload = json.dumps({
  "prompt": "A calm and relaxing piano track with soft melodies",
  "style": "Classical",
  "title": "Peaceful Piano Meditation",
  "customMode": True,
  "instrumental": True,
  "model": "V3_5",
  "negativeTags": "Heavy Metal, Upbeat Drums",
  "callBackUrl": "https://api.example.com/callback"
})
headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'Authorization': 'Bearer ' + token
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

# 오디오 아이디
import requests

url = "https://apibox.erweima.ai/api/v1/generate/record-info?taskId=504c5afa00671aae73bf26c567d3bb53"

headers = {
    'Accept': 'application/json',
    'Authorization': 'Bearer ' + token
}

response = requests.get(url, headers=headers)
print(response.text)

# 보컬 제거
import requests
import json

url = "https://apibox.erweima.ai/api/v1/vocal-removal/generate"

payload = json.dumps({
  "taskId": "504c5afa00671aae73bf26c567d3bb53",
  "audioId": "11944685-1b1c-46d9-8d10-a19280ec1214",
  "callBackUrl": "https://webhook.site/#!/view/02c1b091-838a-425b-9c93-47835ad21962"
})

headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'Authorization': 'Bearer ' + token
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

url = "https://apibox.erweima.ai/api/v1/generate"

payload = json.dumps({
  "prompt": "중2때까진 늘 첫째 줄에\n겨우 160이 됐을 무렵\n쓸만한 녀석들은 모두 다\n이미 첫사랑 진행 중\n정말 듣고 싶었던 말이야\n물론 2년전 일이지만\n기뻐야하는 게 당연한데\n내 기분은 그게 아냐\n하지만 미안해 네 넓은 가슴에 묻혀\n다른 누구를 생각했었어\n미안해 너의 손을 잡고 걸을 때에도\n떠올렸었어 그 사람을\n널 좋아하면 좋아할수록\n상처 입은 날들이 더 많아\n모두가 즐거운 한 때에도\n나는 늘 그곳에 없어\n정말 미안한 일을 한걸까\n나쁘진 않았었지만\n친구인 채였다면 오히려\n즐거웠을 것만 같아\n하지만 미안해 네 넓은 가슴에 묻혀\n다른 누구를 생각했었어\n미안해 너의 손을 잡고 걸을 때에도\n떠올랐었어 그 사람이\n정말 듣고 싶었던 말이야\n물론 2년전 일이지만\n기뻐야하는 게 당연한데\n내 기",
  "style": "Disco",
  "title": "discoback",
  "customMode": True,
  "instrumental": False,
  "model": "V3_5",
  "negativeTags": "classic style",
  "callBackUrl": "https://api.example.com/callback"
})
headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'Authorization': 'Bearer ' + token
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

# 오디오 아이디
import requests

url = "https://apibox.erweima.ai/api/v1/generate/record-info?taskId=6d85723447963eae0ed9a41f74cd4687"

headers = {
    'Accept': 'application/json',
    'Authorization': 'Bearer ' + token
}

response = requests.get(url, headers=headers)
print(response.text)
# print(json.dumps(response.text, indent=4, ensure_ascii=False))

# response_data = json.loads(response.text)

# # 2차 파싱: param 안의 JSON 문자열 다시 파싱
# param_str = response_data["data"]["param"]
# parsed_param = json.loads(param_str)

# # 보기 좋게 출력
# print(json.dumps(parsed_param, indent=4, ensure_ascii=False))

# a9efe60b-7436-420f-9e5f-b6bb16e1061c

# 보컬 제거
import requests
import json

url = "https://apibox.erweima.ai/api/v1/vocal-removal/generate"

payload = json.dumps({
  "taskId": "6d85723447963eae0ed9a41f74cd4687",
  "audioId": "9351f519-6dbf-4104-b4b9-99d07a54e9da",
  "callBackUrl": "https://webhook.site/#!/view/02c1b091-838a-425b-9c93-47835ad21962"
})

headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'Authorization': 'Bearer ' + token
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

# 오디오 아이디
import requests

url = "https://apibox.erweima.ai/api/v1/generate/record-info?taskId=b749664764f3dbadc4246d71c0b79188"

headers = {
    'Accept': 'application/json',
    'Authorization': 'Bearer ' + token
}

response = requests.get(url, headers=headers)
print(response.text)