# -*- coding: utf-8 -*-
"""murekatest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yoaToHhV3qxd__0uAaGBBWdnm6WobCu
"""

token = "token"

import requests
import json

music1 = "/content/music1.mp3"
music2 = "/content/music2.mp3"

url = "https://api.mureka.ai/v1/files/upload"

headers = {
    "Authorization": "Bearer "  + token
}

files = {
    "file": (music1, open(music1, "rb"), "audio/mpeg")
}

data = {
    "purpose": "melody"
}

response = requests.post(url, headers=headers, files=files, data=data)

print(response.status_code)
print(response.json())

url = "https://api.mureka.ai/v1/files/upload"

headers = {
    "Authorization": "Bearer "  + token
}

files = {
    "file": (music2, open(music2, "rb"), "audio/mpeg")
}

data = {
    "purpose": "vocal"
}

response = requests.post(url, headers=headers, files=files, data=data)

print(response.status_code)
print(response.json())

url = "https://api.mureka.ai/v1/song/generate"
headers = {
    "Authorization": "Bearer " + token,
    "Content-Type": "application/json"
}
payload = {
    "lyrics": """중2때까진 늘 첫째 줄에\n겨우 160이 됐을 무렵\n쓸만한 녀석들은 모두 다\n이미 첫사랑 진행 중""",
    "melody_id" : "72350582177793"
}

response = requests.post(url, headers=headers, data=json.dumps(payload))

print(response.status_code)
print(response.json())