# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3TwCN_cN7SA7mf8xewRt-4rN9WAzFQn
"""

!pip install pymysql sqlalchemy asyncio aiomysql

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = (
    "mysql+pymysql://root:1q2w3e@svc.sel4.cloudtype.app:31714/songtang?charset=utf8mb4"
)

engine = create_engine(DATABASE_URL, echo=True)
SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)

Base = declarative_base()

from sqlalchemy import create_engine, text

def insert_data(id, title, length, emotion):
    engine = create_engine(DATABASE_URL, echo=True)
    try:
        with engine.connect() as conn:
            trans = conn.begin()
            conn.execute(
                text("INSERT INTO sample_songs (id, title, length, emotion) VALUES (:id, :title, :length, :emotion)"),
                {"id": id, "title": title, "length": length, "emotion" : emotion}
            )
            trans.commit()
            result = conn.execute(text("SELECT * FROM sample_songs"))
            rows = result.fetchall()
            for row in rows:
                print(row)
        print("✅ 쿼리 실행 성공")
    except Exception as e:
        print("❌ 쿼리 실행 실패:", e)

# joy

# sadness

# anger

# calm

# excitement

# hope

# love

# anxiety

prompts_lists = [
  prompts_sadness,
  prompts_anger,
  prompts_calm,
  prompts_excitement,
  prompts_hope,
  prompts_love,
  prompts_anxiety,
  prompt_joy
]

token = "token"

import requests
import json

task_ids = []

for prompt_list in prompts_lists:
    for p in prompt_list:
        url = "https://apibox.erweima.ai/api/v1/generate"

        prompt = p["prompt"]
        style = p["style"]
        title = p["title"]

        payload = json.dumps({
        "prompt": prompt,
        "style": style,
        "title": title,
        "customMode": True,
        "instrumental": True,
        "model": "V4_5",
        "callBackUrl": "https://your-api.com/music-callback"
        })

        headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
        }
        response = requests.request("POST", url, headers=headers, data=payload)

        task_ids.append(json.loads(response.text)["data"]["taskId"])

        print(response.text)

task_ids = """
147ea9d2a0de7f9524e9175d53f52b77
f837fc3caf7adc7cce3d683b3cf3c7ea
489f631851e8c3a1b784a1dc169d1106
881e4b80a5cca45f95571812aa9695e5
e1c0916d4304aebc9b42397166448728
4d8b08198b48c04aeb5fa7007c55779c
f31b9fcc4ae74a20361fff13157c9e6e
c2927d9fcd105081ef6414f55d7d78a5
4a138a62d976f83d866f754e9f018aed
d7791b8837685fadc28c119d68718760
0bad21e30b18c7fe12d334f9c0c748a4
29d9da368753968ed1e9085a9c06702c
a5aff4e5a162e6a3f83ddbdb58cf2aec
2e368bfe3162fc6be28a60aa6310b056
2a3f98c2f4307feeb786309dbc68c66f
56aca0ee63a1632b7811f92f2f1bce2e
24776eb3f44be393c9ac11c73554a0c6
e4a3c8c638f157a54e73292920fabb87
da9dcdd3a15ada8e26027655d4ac3816
76b9a094cc3098383824bf2a7e408bca
7431d3a507927f30e4d4e94b5b4f25f3
23272c8369ab81300726826d623389ae
cfa7edcc4461b0987d9dcacb101599f1
55a59e287ac8d5b5127c9692ad9c4159
f267fafb436914eb5b006cc690273ff0
f58c28b7bc6f54f6bb8397777168263f
b0f9b760cf82a1ac96d304e235d06dc7
095ab060a2bd96c018265099586e895d
2f2f1e9810b4d799e964c672a69e55e1
bfe5391e1619bf8f7e644ba8bb2d9816
fe4dfa104fbda627113ef580cf3e39dd
b27ffa2aaf0e6eaa53b1752b8f5d2798
99a6d74802cb2175e9b2035189ebcb71
b0004af92016607f5489c034f3168278
979140e31656c1634b2c71ff4b267459
e00eb5e96131e8debd7809062d160284
8eb4737aaecda829bead25a1e67008fb
3d1a08a5aac6688ae332d031c6453073
90f4595127eb1ca98a3fb7f3bff6e1ac
dc8b1df31c42b4d9574524cd41497ee3
dae7541468853f2b67a78ee033abc8d7
a3bd97b4aeb8d9994a3e8aeca87fbaf3
8c70497c9990a8261f72899fd308e2fb
66c53dfb9c932b547e59cf63bb0fd1a2
e2f192b88d20db4d1019167a0be91ad3
3a2f768c186bb4d824aee94caec7c385
60051ef81db10e9502645b2014e18c18
2650ed2889767ce2de5f99a36750c6ea
96925067beb6fb15b967df0ac6a154fb
9d6d8907811af3c8c044e92c530ac7f5
0ac1a90b7c44a4b3ff2b7ed78d1b7c56
7057bd792294594326f8e453f6db1a4d
55c47fdf6523ec6a1ed0e6922c393e55
614897af0017ecdd905dba85de2f8490
df3fe122fdb1dbc0fa70f927ac7f392a
7b028eaf50f6a8d793fa95320e649320
97963b651f6dbf86de7eb9787bf900db
f5e701ba90dad96bd564856cd6618940
34c649a9e517b029f8ddd50c18e89982
247c947b1fdfbf661379f7d2e37a274f
87e3690c64c8198d81aeb6d04767365a
50fcabbac39f078f707a2399207144a9
82704e07d0e2a60c94afd6f6bcb06f6f
0d1c8d6e49c4d13dbd4e0cd4dcef6f84
88d8deee9bb895e599f3a523f0248e97
caf80d359a536ced9c2625cec2cdeebe
5ef667222919d6a15c5c4e67f3d5db2b
cd92bb1d3b18599d87911f8adfdd83ed
7ff38387148a4f6ae079cc620e0525f8
ae0ba04881a31048c8e403fc971e2dec
3f09d183a6815ed19dd026627a69984a
2f345e793bfbb430d19861feee8b2f05
f4eb145e65f9d099ea19d07ff555ff87
2203ae7732f703b38a03d5c5fd2c28fd
2b90a691ff58da6d855a2025c5a58c59
59302e9f71f0f64dea90d66f05b8e036
55f4851a10cee84e50e6b6c3a74e5f72
e21daf41c1752ae56ea4cd54f1bc2a49
16a5aa713e4bfd8e2f40752f1d8653f3
d17f9da6d136f7a516372fc4f04175ab
""".split("\n")

len(task_ids[1:-1])
for id in task_ids:
    print(id)

task_ids = task_ids[1:-1]
len(task_ids)

first = task_ids[:10]
second = task_ids[10:20]
third = task_ids[20:30]
fourth = task_ids[30:40]
fifth = task_ids[40:50]
sixth = task_ids[50:60]
seventh = task_ids[60:70]
eighth = task_ids[70:]

songs = []

from types import resolve_bases
import requests

firstt = []

for id in first:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    firstt.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    firstt.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

secondd = []
for id in second:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    secondd.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    secondd.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

thirdd = []

for id in third:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    thirdd.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    thirdd.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

fourthh = []

for id in fourth:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    fourthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    fourthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

fifthh = []

for id in fifth:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    fifthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    fifthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

sixthh = []

for id in sixth:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    sixthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    sixthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

seventhh = []

for id in seventh:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    seventhh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    seventhh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

eighthh = []

for id in eighth:
    url = f"https://apibox.erweima.ai/api/v1/generate/record-info?taskId={id}"

    headers = {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token
    }

    response = requests.get(url, headers=headers)

    eighthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][0]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][0]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][0]["duration"]
    })

    eighthh.append({
        "title" : json.loads( response.text)["data"]['response']["sunoData"][1]["title"],
        "id" : json.loads( response.text)["data"]['response']["sunoData"][1]['id'],
        "length" : json.loads( response.text)["data"]['response']["sunoData"][1]["duration"]
    })

    print(response.text)

songs = firstt + secondd + thirdd + fourthh + fifthh + sixthh + seventhh + eighthh
emotions = ["sadness", "anger", "calm", "excitement", "hope", "love", "anxiety", "joy"]
print(len(songs))
for i in range(len(songs)):
    songs[i]["emotion"] = emotions[i // 20]

for song in songs:
    print(song)

for song in songs:
    # print(f'id: {song["id"]} / title: {song["title"]} / length: {song["length"]} / emotion: {song["emotion"]}')
    insert_data(song["id"], song["title"], song["length"], song["emotion"])

from sqlalchemy import create_engine, text

def select_all_data():
    engine = create_engine(DATABASE_URL, echo=True)
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT * FROM sample_songs"))
            rows = result.fetchall()
            print(len(rows))
            for row in rows:
                print(row)
        print("✅ 쿼리 실행 성공")
    except Exception as e:
        print("❌ 쿼리 실행 실패:", e)

select_all_data()